import type { Node } from "../types/node";

export const mockNodes: Node = {
  id: "root",
  name: "Root",
  type: "Div",
  x: 0,
  y: 0,
  width: 600,
  height: 400,
  background: "#f0f0f0",
  children: [
    {
      id: "text1",
      name: "Text 1",
      type: "Div",
      x: 20,
      y: 20,
      width: 560,
      height: 60,
      background: "#ffd700",
      color: "#333",
      text: "Text 2",
      children: [],
    },
    {
      id: "container1",
      name: "Node 2",
      type: "Div",
      x: 20,
      y: 100,
      width: 560,
      height: 120,
      background: "#28a745",
      children: [
        {
          id: "button1",
          name: "Button 1",
          type: "Button",
          x: 40,
          y: 120,
          width: 520,
          height: 40,
          background: "#007bff",
          color: "white",
          text: "Button 1",
          children: [],
        },
        {
          id: "image1",
          name: "Image 1",
          type: "Image",
          x: 40,
          y: 170,
          width: 520,
          height: 40,
          background: "#e83e8c",
          children: [],
        },
      ],
    },
    {
      id: "container2",
      name: "Node 4",
      type: "Div",
      x: 20,
      y: 240,
      width: 560,
      height: 120,
      background: "#28a745",
      children: [
        {
          id: "button2",
          name: "Button 2",
          type: "Button",
          x: 40,
          y: 260,
          width: 520,
          height: 40,
          background: "#007bff",
          color: "white",
          text: "Button 2",
          children: [],
        },
        {
          id: "image2",
          name: "Image 2",
          type: "Image",
          x: 40,
          y: 310,
          width: 520,
          height: 40,
          background: "#e83e8c",
          children: [],
        },
      ],
    },
  ],
};

export const mockNodes2: Node = {
  id: "root",
  x: 0,
  y: 0,
  name: "App Container",
  type: "Div",
  width: 800,
  height: 600,
  background: "#ffffff",
  border: "1px solid #e5e7eb",
  children: [
    {
      id: "header",
      x: 20,
      y: 20,
      name: "Header",
      type: "Div",
      width: 760,
      height: 80,
      background: "#f3f4f6",
      border: "1px solid #d1d5db",
      children: [
        {
          id: "logo",
          x: 40,
          y: 40,
          name: "Logo",
          type: "Image",
          width: 60,
          height: 40,
          background: "#3b82f6",
          children: [],
        },
        {
          id: "nav",
          x: 120,
          y: 40,
          name: "Navigation",
          type: "Div",
          width: 400,
          height: 40,
          background: "transparent",
          children: [
            {
              id: "nav-item-1",
              x: 120,
              y: 40,
              name: "Home",
              type: "Button",
              width: 80,
              height: 40,
              background: "#3b82f6",
              color: "#ffffff",
              text: "Home",
              children: [],
            },
            {
              id: "nav-item-2",
              x: 220,
              y: 40,
              name: "About",
              type: "Button",
              width: 80,
              height: 40,
              background: "#6b7280",
              color: "#ffffff",
              text: "About",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: "main",
      x: 20,
      y: 120,
      name: "Main Content",
      type: "Div",
      width: 760,
      height: 400,
      background: "#ffffff",
      border: "1px solid #e5e7eb",
      children: [
        {
          id: "form",
          x: 40,
          y: 140,
          name: "Contact Form",
          type: "Div",
          width: 300,
          height: 200,
          background: "#f9fafb",
          border: "1px solid #d1d5db",
          children: [
            {
              id: "input-name",
              x: 60,
              y: 160,
              name: "Name Input",
              type: "Input",
              width: 260,
              height: 40,
              background: "#ffffff",
              border: "1px solid #d1d5db",
              children: [],
            },
            {
              id: "input-email",
              x: 60,
              y: 220,
              name: "Email Input",
              type: "Input",
              width: 260,
              height: 40,
              background: "#ffffff",
              border: "1px solid #d1d5db",
              children: [],
            },
            {
              id: "submit-btn",
              x: 60,
              y: 280,
              name: "Submit Button",
              type: "Button",
              width: 100,
              height: 40,
              background: "#10b981",
              color: "#ffffff",
              text: "Submit",
              children: [],
            },
          ],
        },
        {
          id: "sidebar",
          x: 400,
          y: 140,
          name: "Sidebar",
          type: "Div",
          width: 320,
          height: 360,
          background: "#f3f4f6",
          border: "1px solid #d1d5db",
          children: [
            {
              id: "sidebar-title",
              x: 420,
              y: 160,
              name: "Sidebar Title",
              type: "Div",
              width: 280,
              height: 40,
              background: "#1f2937",
              color: "#ffffff",
              text: "Quick Links",
              children: [],
            },
            {
              id: "link-1",
              x: 420,
              y: 220,
              name: "Link 1",
              type: "Button",
              width: 280,
              height: 30,
              background: "transparent",
              color: "#374151",
              text: "Documentation",
              border: "1px solid #d1d5db",
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
