import type { Node } from "../types/node";

export const mockNodes: Node = {
  id: "0:0",
  name: "Document",
  type: "Div",
  x: 0,
  y: 0,
  width: 100,
  height: 100,
  children: [
    {
      id: "0:1",
      name: "Page 1",
      type: "Div",
      x: 0,
      y: 0,
      width: 100,
      height: 100,
      children: [
        {
          id: "0:8",
          name: "Frame 23928",
          type: "Div",
          x: 0,
          y: 0,
          width: 375,
          height: 384,
          children: [
            {
              id: "0:9",
              name: "Title",
              type: "Div",
              x: 16,
              y: 12,
              width: 343,
              height: 20,
              children: [
                {
                  id: "0:10",
                  name: "Gợi ý trạng thái",
                  type: "Div",
                  x: 16,
                  y: 0,
                  width: 112,
                  height: 16,
                  background: "#73787e",
                  text: "Gợi ý trạng thái",
                  children: [],
                },
              ],
            },
            {
              id: "0:11",
              name: "Options",
              type: "Div",
              x: 16,
              y: 32,
              width: 343,
              height: 340,
              background: "#ffffff",
              borderRadius: "12px",
              children: [
                {
                  id: "0:12",
                  name: "In a meeting",
                  type: "Div",
                  x: 0,
                  y: 0,
                  width: 343,
                  height: 68,
                  borderRadius: "8px",
                  children: [
                    {
                      id: "0:13",
                      name: "prohibition 1",
                      type: "Div",
                      x: 16,
                      y: 22,
                      width: 24,
                      height: 24,
                      background: "#ffffff",
                      children: [],
                    },
                    {
                      id: "0:19",
                      name: "Frame 23917",
                      type: "Div",
                      x: 52,
                      y: 12,
                      width: 73,
                      height: 44,
                      children: [
                        {
                          id: "0:20",
                          name: "Đang bận",
                          type: "Div",
                          x: 0,
                          y: 0,
                          width: 73,
                          height: 24,
                          background: "#18202a",
                          text: "Đang bận",
                          children: [],
                        },
                        {
                          id: "0:21",
                          name: "Hôm nay",
                          type: "Div",
                          x: 0,
                          y: 24,
                          width: 59,
                          height: 20,
                          background: "#73787e",
                          text: "Hôm nay",
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "0:22",
                  name: "In a meeting",
                  type: "Div",
                  x: 0,
                  y: 68,
                  width: 343,
                  height: 68,
                  borderRadius: "8px",
                  children: [
                    {
                      id: "0:23",
                      name: "meeting 1",
                      type: "Div",
                      x: 16,
                      y: 22,
                      width: 24,
                      height: 24,
                      background: "#ffffff",
                      children: [],
                    },
                    {
                      id: "0:41",
                      name: "Frame 23917",
                      type: "Div",
                      x: 52,
                      y: 12,
                      width: 118,
                      height: 44,
                      children: [
                        {
                          id: "0:42",
                          name: "Trong cuộc họp",
                          type: "Div",
                          x: 0,
                          y: 0,
                          width: 118,
                          height: 24,
                          background: "#18202a",
                          text: "Trong cuộc họp",
                          children: [],
                        },
                        {
                          id: "0:43",
                          name: "1 giờ",
                          type: "Div",
                          x: 0,
                          y: 24,
                          width: 32,
                          height: 20,
                          background: "#73787e",
                          text: "1 giờ",
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "0:44",
                  name: "In a meeting",
                  type: "Div",
                  x: 0,
                  y: 136,
                  width: 343,
                  height: 68,
                  borderRadius: "8px",
                  children: [
                    {
                      id: "0:45",
                      name: "car-wash 1",
                      type: "Div",
                      x: 16,
                      y: 22,
                      width: 24,
                      height: 24,
                      background: "#ffffff",
                      children: [],
                    },
                    {
                      id: "0:63",
                      name: "Frame 23917",
                      type: "Div",
                      x: 52,
                      y: 12,
                      width: 117,
                      height: 44,
                      children: [
                        {
                          id: "0:64",
                          name: "Có việc ở ngoài",
                          type: "Div",
                          x: 0,
                          y: 0,
                          width: 117,
                          height: 24,
                          background: "#18202a",
                          text: "Có việc ở ngoài",
                          children: [],
                        },
                        {
                          id: "0:65",
                          name: "30 phút",
                          type: "Div",
                          x: 0,
                          y: 24,
                          width: 52,
                          height: 20,
                          background: "#73787e",
                          text: "30 phút",
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "0:66",
                  name: "In a meeting",
                  type: "Div",
                  x: 0,
                  y: 204,
                  width: 343,
                  height: 68,
                  borderRadius: "8px",
                  children: [
                    {
                      id: "0:67",
                      name: "calendar 1",
                      type: "Div",
                      x: 16,
                      y: 22,
                      width: 24,
                      height: 24,
                      background: "#ffffff",
                      children: [],
                    },
                    {
                      id: "0:90",
                      name: "Frame 23917",
                      type: "Div",
                      x: 52,
                      y: 12,
                      width: 62,
                      height: 44,
                      children: [
                        {
                          id: "0:91",
                          name: "Xin nghỉ",
                          type: "Div",
                          x: 0,
                          y: 0,
                          width: 62,
                          height: 24,
                          background: "#18202a",
                          text: "Xin nghỉ",
                          children: [],
                        },
                        {
                          id: "0:92",
                          name: "Hôm nay",
                          type: "Div",
                          x: 0,
                          y: 24,
                          width: 59,
                          height: 20,
                          background: "#73787e",
                          text: "Hôm nay",
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "0:93",
                  name: "In a meeting",
                  type: "Div",
                  x: 0,
                  y: 272,
                  width: 343,
                  height: 68,
                  borderRadius: "8px",
                  children: [
                    {
                      id: "0:94",
                      name: "work-from-home 1",
                      type: "Div",
                      x: 16,
                      y: 22,
                      width: 24,
                      height: 24,
                      background: "#ffffff",
                      children: [],
                    },
                    {
                      id: "0:142",
                      name: "Frame 23917",
                      type: "Div",
                      x: 52,
                      y: 12,
                      width: 114,
                      height: 44,
                      children: [
                        {
                          id: "0:143",
                          name: "Làm việc ở nhà",
                          type: "Div",
                          x: 0,
                          y: 0,
                          width: 114,
                          height: 24,
                          background: "#18202a",
                          text: "Làm việc ở nhà",
                          children: [],
                        },
                        {
                          id: "0:144",
                          name: "Hôm nay",
                          type: "Div",
                          x: 0,
                          y: 24,
                          width: 59,
                          height: 20,
                          background: "#73787e",
                          text: "Hôm nay",
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "0:145",
                  name: "Add-Fields",
                  type: "Div",
                  x: 0,
                  y: 92,
                  width: 353,
                  height: 40,
                  background: "#ffffff",
                  borderRadius: "8px",
                  children: [],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const loginUIData: Node = {
  id: "root",
  x: 0,
  y: 0,
  name: "LoginContainer",
  type: "Div",
  width: 546,
  height: 600,
  background: "#ffffff",
  display: "flex",
  children: [
    // Welcome Title
    {
      id: "welcome-title",
      x: 38,
      y: 25,
      name: "WelcomeTitle",
      type: "Div",
      width: 470,
      height: 60,
      text: "Welcome fellow Loco!",
      color: "#1a365d",
      children: [],
    },

    // Continue with section
    {
      id: "continue-section",
      x: 38,
      y: 85,
      name: "ContinueSection",
      type: "Div",
      width: 470,
      height: 150,
      children: [
        {
          id: "continue-title",
          x: 0,
          y: 0,
          name: "ContinueTitle",
          type: "Div",
          width: 470,
          height: 20,
          text: "Continue with",
          color: "#4a5568",
          children: [],
        },

        // OAuth buttons container
        {
          id: "oauth-container",
          x: 0,
          y: 30,
          name: "OAuthContainer",
          type: "Div",
          width: 470,
          height: 100,
          display: "flex",
          children: [
            // Google OAuth Button
            {
              id: "google-oauth",
              x: 0,
              y: 0,
              name: "OAuthButton",
              type: "Button",
              width: 150,
              height: 80,
              background: "#ffffff",
              borderRadius: "8px",
              border: "1px solid #e2e8f0",
              children: [
                {
                  id: "google-icon",
                  x: 50,
                  y: 5,
                  name: "OAuthIcon",
                  type: "Image",
                  width: 50,
                  height: 50,
                  children: [],
                },
                {
                  id: "google-text",
                  x: 0,
                  y: 50,
                  name: "OAuthText",
                  type: "Div",
                  width: 150,
                  height: 20,
                  text: "Google",
                  color: "#1a202c",
                  children: [],
                },
              ],
            },

            // GitHub OAuth Button
            {
              id: "github-oauth",
              x: 160,
              y: 0,
              name: "OAuthButton",
              type: "Button",
              width: 150,
              height: 80,
              background: "#ffffff",
              borderRadius: "8px",
              border: "1px solid #e2e8f0",
              children: [
                {
                  id: "github-icon",
                  x: 50,
                  y: 5,
                  name: "OAuthIcon",
                  type: "Image",
                  width: 50,
                  height: 50,
                  children: [],
                },
                {
                  id: "github-text",
                  x: 0,
                  y: 50,
                  name: "OAuthText",
                  type: "Div",
                  width: 150,
                  height: 20,
                  text: "Github",
                  color: "#1a202c",
                  children: [],
                },
              ],
            },

            // SAML SSO Button
            {
              id: "saml-oauth",
              x: 320,
              y: 0,
              name: "OAuthButton",
              type: "Button",
              width: 150,
              height: 80,
              background: "#ffffff",
              borderRadius: "8px",
              border: "1px solid #e2e8f0",
              children: [
                {
                  id: "saml-icon",
                  x: 50,
                  y: 5,
                  name: "OAuthIcon",
                  type: "Image",
                  width: 50,
                  height: 50,
                  children: [],
                },
                {
                  id: "saml-text",
                  x: 0,
                  y: 50,
                  name: "OAuthText",
                  type: "Div",
                  width: 150,
                  height: 20,
                  text: "SAML SSO",
                  color: "#1a202c",
                  children: [],
                },
              ],
            },
          ],
        },
      ],
    },

    // Email section
    {
      id: "email-section",
      x: 38,
      y: 255,
      name: "EmailSection",
      type: "Div",
      width: 470,
      height: 200,
      children: [
        {
          id: "email-title",
          x: 0,
          y: 0,
          name: "EmailTitle",
          type: "Div",
          width: 470,
          height: 20,
          text: "Or, sign-in with your email",
          color: "#4a5568",
          children: [],
        },

        // Email input field
        {
          id: "email-field",
          x: 0,
          y: 35,
          name: "InputField",
          type: "Div",
          width: 470,
          height: 44,
          background: "#f7fafc",
          border: "1px solid #e2e8f0",
          borderRadius: "4px",
          children: [
            {
              id: "email-icon",
              x: 5,
              y: 7,
              name: "InputIcon",
              type: "Image",
              width: 30,
              height: 30,
              children: [],
            },
            {
              id: "email-input",
              x: 35,
              y: 0,
              name: "InputControl",
              type: "Input",
              width: 425,
              height: 44,
              text: "Email",
              color: "#a0aec0",
              background: "transparent",
              border: "none",
              children: [],
            },
          ],
        },

        // Password input field
        {
          id: "password-field",
          x: 0,
          y: 85,
          name: "InputField",
          type: "Div",
          width: 470,
          height: 44,
          background: "#f7fafc",
          border: "1px solid #e2e8f0",
          borderRadius: "4px",
          children: [
            {
              id: "password-icon",
              x: 5,
              y: 7,
              name: "InputIcon",
              type: "Image",
              width: 30,
              height: 30,
              children: [],
            },
            {
              id: "password-input",
              x: 35,
              y: 0,
              name: "InputControl",
              type: "Input",
              width: 425,
              height: 44,
              text: "Password",
              color: "#a0aec0",
              background: "transparent",
              border: "none",
              children: [],
            },
          ],
        },

        // Forgot password link
        {
          id: "forgot-password",
          x: 280,
          y: 135,
          name: "ForgotPassword",
          type: "Button",
          width: 240,
          height: 20,
          text: "🔒 Forgot Password?",
          color: "#4299e1",
          background: "transparent",
          border: "none",
          children: [],
        },

        // Sign In button
        {
          id: "signin-button",
          x: 0,
          y: 180,
          name: "SignInButton",
          type: "Button",
          width: 470,
          height: 50,
          text: "Sign In",
          color: "#ffffff",
          background: "#4299e1",
          borderRadius: "8px",
          border: "none",
          children: [],
        },
      ],
    },
  ],
};

export const mockNodes2: Node = {
  id: "root",
  x: 0,
  y: 0,
  name: "App Container",
  type: "Div",
  width: 800,
  height: 600,
  background: "#ffffff",
  border: "1px solid #e5e7eb",
  children: [
    {
      id: "header",
      x: 20,
      y: 20,
      name: "Header",
      type: "Div",
      width: 760,
      height: 80,
      background: "#f3f4f6",
      border: "1px solid #d1d5db",
      children: [
        {
          id: "logo",
          x: 40,
          y: 40,
          name: "Logo",
          type: "Image",
          width: 60,
          height: 40,
          background: "#3b82f6",
          children: [],
        },
        {
          id: "nav",
          x: 120,
          y: 40,
          name: "Navigation",
          type: "Div",
          width: 400,
          height: 40,
          background: "transparent",
          children: [
            {
              id: "nav-item-1",
              x: 120,
              y: 40,
              name: "Home",
              type: "Button",
              width: 80,
              height: 40,
              background: "#3b82f6",
              color: "#ffffff",
              text: "Home",
              children: [],
            },
            {
              id: "nav-item-2",
              x: 220,
              y: 40,
              name: "About",
              type: "Button",
              width: 80,
              height: 40,
              background: "#6b7280",
              color: "#ffffff",
              text: "About",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: "main",
      x: 20,
      y: 120,
      name: "Main Content",
      type: "Div",
      width: 760,
      height: 400,
      background: "#ffffff",
      border: "1px solid #e5e7eb",
      children: [
        {
          id: "form",
          x: 40,
          y: 140,
          name: "Contact Form",
          type: "Div",
          width: 300,
          height: 200,
          background: "#f9fafb",
          border: "1px solid #d1d5db",
          children: [
            {
              id: "input-name",
              x: 60,
              y: 160,
              name: "Name Input",
              type: "Input",
              width: 260,
              height: 40,
              background: "#ffffff",
              border: "1px solid #d1d5db",
              children: [],
            },
            {
              id: "input-email",
              x: 60,
              y: 220,
              name: "Email Input",
              type: "Input",
              width: 260,
              height: 40,
              background: "#ffffff",
              border: "1px solid #d1d5db",
              children: [],
            },
            {
              id: "submit-btn",
              x: 60,
              y: 280,
              name: "Submit Button",
              type: "Button",
              width: 100,
              height: 40,
              background: "#10b981",
              color: "#ffffff",
              text: "Submit",
              children: [],
            },
          ],
        },
        {
          id: "sidebar",
          x: 400,
          y: 140,
          name: "Sidebar",
          type: "Div",
          width: 320,
          height: 360,
          background: "#f3f4f6",
          border: "1px solid #d1d5db",
          children: [
            {
              id: "sidebar-title",
              x: 420,
              y: 160,
              name: "Sidebar Title",
              type: "Div",
              width: 280,
              height: 40,
              background: "#1f2937",
              color: "#ffffff",
              text: "Quick Links",
              children: [],
            },
            {
              id: "link-1",
              x: 420,
              y: 220,
              name: "Link 1",
              type: "Button",
              width: 280,
              height: 30,
              background: "transparent",
              color: "#374151",
              text: "Documentation",
              border: "1px solid #d1d5db",
              children: [],
            },
          ],
        },
      ],
    },
  ],
};

export const mockNodesWithOverlap: Node = {
  id: "root",
  name: "Root",
  type: "Div",
  x: 0,
  y: 0,
  width: 600,
  height: 400,
  background: "#f0f0f0",
  children: [
    {
      id: "container1",
      name: "Container 1",
      type: "Div",
      x: 50,
      y: 50,
      width: 300,
      height: 200,
      background: "#ff6b6b",
      children: [
        {
          id: "container2",
          name: "Container 2",
          type: "Div",
          x: 50,
          y: 50,
          width: 250,
          height: 150,
          background: "#4ecdc4",
          children: [
            {
              id: "button1",
              name: "Button 1",
              type: "Button",
              x: 50,
              y: 50,
              width: 200,
              height: 100,
              background: "#45b7d1",
              color: "white",
              text: "Deepest Button",
              children: [],
            },
          ],
        },
      ],
    },
    // Add another overlapping element
    {
      id: "overlay",
      name: "Overlay",
      type: "Div",
      x: 100,
      y: 100,
      width: 150,
      height: 75,
      background: "rgba(255, 215, 0, 0.7)",
      text: "Overlay Text",
      children: [],
    },
  ],
};
