import type { Node } from "../types/node";

export const mockNodes: Node = {
  id: "root",
  name: "Root",
  type: "Div",
  x: 0,
  y: 0,
  width: 600,
  height: 400,
  background: "#f0f0f0",
  children: [
    {
      id: "text1",
      name: "Text 1",
      type: "Div",
      x: 20,
      y: 20,
      width: 560,
      height: 60,
      background: "#C9C9EE",
      color: "#333",
      text: "Text 2",
      children: [],
    },
    {
      id: "container1",
      name: "Node 2",
      type: "Div",
      x: 20,
      y: 100,
      width: 560,
      height: 120,
      background: "#d5d5d5",
      children: [
        {
          id: "button1",
          name: "Button 1",
          type: "Button",
          x: 40,
          y: 120,
          width: 520,
          height: 40,
          background: "#104F55",
          color: "white",
          text: "Button 1",
          children: [],
        },
        {
          id: "image1",
          name: "Image 1",
          type: "Image",
          x: 40,
          y: 170,
          width: 520,
          height: 40,
          background: "#ffffff",
          children: [],
        },
      ],
    },
    {
      id: "container2",
      name: "Node 4",
      type: "Div",
      x: 20,
      y: 240,
      width: 560,
      height: 120,
      background: "#d5d5d5",
      children: [
        {
          id: "button2",
          name: "Button 2",
          type: "Button",
          x: 40,
          y: 260,
          width: 520,
          height: 40,
          background: "#104F55",
          color: "white",
          text: "Button 2",
          children: [],
        },
        {
          id: "image2",
          name: "Image 2",
          type: "Image",
          x: 40,
          y: 310,
          width: 520,
          height: 40,
          background: "#ffffff",
          children: [],
        },
      ],
    },
  ],
};

export const loginUIData: Node = {
  id: "root",
  x: 0,
  y: 0,
  name: "LoginContainer",
  type: "Div",
  width: 546,
  height: 600,
  background: "#ffffff",
  display: "flex",
  children: [
    // Welcome Title
    {
      id: "welcome-title",
      x: 38,
      y: 25,
      name: "WelcomeTitle",
      type: "Div",
      width: 470,
      height: 60,
      text: "Welcome fellow Loco!",
      color: "#1a365d",
      children: [],
    },

    // Continue with section
    {
      id: "continue-section",
      x: 38,
      y: 85,
      name: "ContinueSection",
      type: "Div",
      width: 470,
      height: 150,
      children: [
        {
          id: "continue-title",
          x: 0,
          y: 0,
          name: "ContinueTitle",
          type: "Div",
          width: 470,
          height: 20,
          text: "Continue with",
          color: "#4a5568",
          children: [],
        },

        // OAuth buttons container
        {
          id: "oauth-container",
          x: 0,
          y: 30,
          name: "OAuthContainer",
          type: "Div",
          width: 470,
          height: 100,
          display: "flex",
          children: [
            // Google OAuth Button
            {
              id: "google-oauth",
              x: 0,
              y: 0,
              name: "OAuthButton",
              type: "Button",
              width: 150,
              height: 80,
              background: "#ffffff",
              borderRadius: "8px",
              border: "1px solid #e2e8f0",
              children: [
                {
                  id: "google-icon",
                  x: 50,
                  y: 5,
                  name: "OAuthIcon",
                  type: "Image",
                  width: 50,
                  height: 50,
                  children: [],
                },
                {
                  id: "google-text",
                  x: 0,
                  y: 50,
                  name: "OAuthText",
                  type: "Div",
                  width: 150,
                  height: 20,
                  text: "Google",
                  color: "#1a202c",
                  children: [],
                },
              ],
            },

            // GitHub OAuth Button
            {
              id: "github-oauth",
              x: 160,
              y: 0,
              name: "OAuthButton",
              type: "Button",
              width: 150,
              height: 80,
              background: "#ffffff",
              borderRadius: "8px",
              border: "1px solid #e2e8f0",
              children: [
                {
                  id: "github-icon",
                  x: 50,
                  y: 5,
                  name: "OAuthIcon",
                  type: "Image",
                  width: 50,
                  height: 50,
                  children: [],
                },
                {
                  id: "github-text",
                  x: 0,
                  y: 50,
                  name: "OAuthText",
                  type: "Div",
                  width: 150,
                  height: 20,
                  text: "Github",
                  color: "#1a202c",
                  children: [],
                },
              ],
            },

            // SAML SSO Button
            {
              id: "saml-oauth",
              x: 320,
              y: 0,
              name: "OAuthButton",
              type: "Button",
              width: 150,
              height: 80,
              background: "#ffffff",
              borderRadius: "8px",
              border: "1px solid #e2e8f0",
              children: [
                {
                  id: "saml-icon",
                  x: 50,
                  y: 5,
                  name: "OAuthIcon",
                  type: "Image",
                  width: 50,
                  height: 50,
                  children: [],
                },
                {
                  id: "saml-text",
                  x: 0,
                  y: 50,
                  name: "OAuthText",
                  type: "Div",
                  width: 150,
                  height: 20,
                  text: "SAML SSO",
                  color: "#1a202c",
                  children: [],
                },
              ],
            },
          ],
        },
      ],
    },

    // Email section
    {
      id: "email-section",
      x: 38,
      y: 255,
      name: "EmailSection",
      type: "Div",
      width: 470,
      height: 200,
      children: [
        {
          id: "email-title",
          x: 0,
          y: 0,
          name: "EmailTitle",
          type: "Div",
          width: 470,
          height: 20,
          text: "Or, sign-in with your email",
          color: "#4a5568",
          children: [],
        },

        // Email input field
        {
          id: "email-field",
          x: 0,
          y: 35,
          name: "InputField",
          type: "Div",
          width: 470,
          height: 44,
          background: "#f7fafc",
          border: "1px solid #e2e8f0",
          borderRadius: "4px",
          children: [
            {
              id: "email-icon",
              x: 5,
              y: 7,
              name: "InputIcon",
              type: "Image",
              width: 30,
              height: 30,
              children: [],
            },
            {
              id: "email-input",
              x: 35,
              y: 0,
              name: "InputControl",
              type: "Input",
              width: 425,
              height: 44,
              text: "Email",
              color: "#a0aec0",
              background: "transparent",
              border: "none",
              children: [],
            },
          ],
        },

        // Password input field
        {
          id: "password-field",
          x: 0,
          y: 85,
          name: "InputField",
          type: "Div",
          width: 470,
          height: 44,
          background: "#f7fafc",
          border: "1px solid #e2e8f0",
          borderRadius: "4px",
          children: [
            {
              id: "password-icon",
              x: 5,
              y: 7,
              name: "InputIcon",
              type: "Image",
              width: 30,
              height: 30,
              children: [],
            },
            {
              id: "password-input",
              x: 35,
              y: 0,
              name: "InputControl",
              type: "Input",
              width: 425,
              height: 44,
              text: "Password",
              color: "#a0aec0",
              background: "transparent",
              border: "none",
              children: [],
            },
          ],
        },

        // Forgot password link
        {
          id: "forgot-password",
          x: 280,
          y: 135,
          name: "ForgotPassword",
          type: "Button",
          width: 240,
          height: 20,
          text: "🔒 Forgot Password?",
          color: "#4299e1",
          background: "transparent",
          border: "none",
          children: [],
        },

        // Sign In button
        {
          id: "signin-button",
          x: 0,
          y: 180,
          name: "SignInButton",
          type: "Button",
          width: 470,
          height: 50,
          text: "Sign In",
          color: "#ffffff",
          background: "#4299e1",
          borderRadius: "8px",
          border: "none",
          children: [],
        },
      ],
    },
  ],
};

export const mockNodes2: Node = {
  id: "root",
  x: 0,
  y: 0,
  name: "App Container",
  type: "Div",
  width: 800,
  height: 600,
  background: "#ffffff",
  border: "1px solid #e5e7eb",
  children: [
    {
      id: "header",
      x: 20,
      y: 20,
      name: "Header",
      type: "Div",
      width: 760,
      height: 80,
      background: "#f3f4f6",
      border: "1px solid #d1d5db",
      children: [
        {
          id: "logo",
          x: 40,
          y: 40,
          name: "Logo",
          type: "Image",
          width: 60,
          height: 40,
          background: "#3b82f6",
          children: [],
        },
        {
          id: "nav",
          x: 120,
          y: 40,
          name: "Navigation",
          type: "Div",
          width: 400,
          height: 40,
          background: "transparent",
          children: [
            {
              id: "nav-item-1",
              x: 120,
              y: 40,
              name: "Home",
              type: "Button",
              width: 80,
              height: 40,
              background: "#3b82f6",
              color: "#ffffff",
              text: "Home",
              children: [],
            },
            {
              id: "nav-item-2",
              x: 220,
              y: 40,
              name: "About",
              type: "Button",
              width: 80,
              height: 40,
              background: "#6b7280",
              color: "#ffffff",
              text: "About",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: "main",
      x: 20,
      y: 120,
      name: "Main Content",
      type: "Div",
      width: 760,
      height: 400,
      background: "#ffffff",
      border: "1px solid #e5e7eb",
      children: [
        {
          id: "form",
          x: 40,
          y: 140,
          name: "Contact Form",
          type: "Div",
          width: 300,
          height: 200,
          background: "#f9fafb",
          border: "1px solid #d1d5db",
          children: [
            {
              id: "input-name",
              x: 60,
              y: 160,
              name: "Name Input",
              type: "Input",
              width: 260,
              height: 40,
              background: "#ffffff",
              border: "1px solid #d1d5db",
              children: [],
            },
            {
              id: "input-email",
              x: 60,
              y: 220,
              name: "Email Input",
              type: "Input",
              width: 260,
              height: 40,
              background: "#ffffff",
              border: "1px solid #d1d5db",
              children: [],
            },
            {
              id: "submit-btn",
              x: 60,
              y: 280,
              name: "Submit Button",
              type: "Button",
              width: 100,
              height: 40,
              background: "#10b981",
              color: "#ffffff",
              text: "Submit",
              children: [],
            },
          ],
        },
        {
          id: "sidebar",
          x: 400,
          y: 140,
          name: "Sidebar",
          type: "Div",
          width: 320,
          height: 360,
          background: "#f3f4f6",
          border: "1px solid #d1d5db",
          children: [
            {
              id: "sidebar-title",
              x: 420,
              y: 160,
              name: "Sidebar Title",
              type: "Div",
              width: 280,
              height: 40,
              background: "#1f2937",
              color: "#ffffff",
              text: "Quick Links",
              children: [],
            },
            {
              id: "link-1",
              x: 420,
              y: 220,
              name: "Link 1",
              type: "Button",
              width: 280,
              height: 30,
              background: "transparent",
              color: "#374151",
              text: "Documentation",
              border: "1px solid #d1d5db",
              children: [],
            },
          ],
        },
      ],
    },
  ],
};

export const mockNodesWithOverlap: Node = {
  id: "root",
  name: "Root",
  type: "Div",
  x: 0,
  y: 0,
  width: 600,
  height: 400,
  background: "#f0f0f0",
  children: [
    {
      id: "container1",
      name: "Container 1",
      type: "Div",
      x: 50,
      y: 50,
      width: 300,
      height: 200,
      background: "#ff6b6b",
      children: [
        {
          id: "container2",
          name: "Container 2",
          type: "Div",
          x: 50,
          y: 50,
          width: 250,
          height: 150,
          background: "#4ecdc4",
          children: [
            {
              id: "button1",
              name: "Button 1",
              type: "Button",
              x: 50,
              y: 50,
              width: 200,
              height: 100,
              background: "#45b7d1",
              color: "white",
              text: "Deepest Button",
              children: [],
            },
          ],
        },
      ],
    },
    // Add another overlapping element
    {
      id: "overlay",
      name: "Overlay",
      type: "Div",
      x: 100,
      y: 100,
      width: 150,
      height: 75,
      background: "rgba(255, 215, 0, 0.7)",
      text: "Overlay Text",
      children: [],
    },
  ],
};
